export const engContent = {
  price: "Price",
  category: "Category",
  description: "Description",
  title: "Title",
  content: "Content",
  price: "Price",
  total_price: "Total price",
  history: "History",
  logout: "Logout",
  login: "Login & Register",
  noProducts: "No Data",
  buy: "Buy",
  view: "View",
  login0: "Login",
  register: "Register",
  notRegister: "Don't have an account. Register?",
  notLogin: "Already have an account. Login?",
  loadMore: "Load more",
  sold: "Sold",
  related: "Related products",
  Newest: "Newest",
  Oldest: "Oldest",
  BestSales: "Best sales",
  LowPrice: "Low price",
  HightPrice: "Hight price",
  delete: "Delete",
  taxrir: "Edit",
  allProducts: "All Products",
  selectDelete: "Delete all",
  selectAll: "Select all",
  products: "Products",
  createProducts: "Create products",
  categories: "Categories",
};
