export const uzContent = {
  price: "Narxi",
  category: "Bo'limi",
  description: "Ta'rifi",
  title: "Sarlavha",
  content: "Ma'lumot",
  price: "Narxi",
  total_price: "Umumiy narx",
  history: "Tarix",
  logout: "Chiqish",
  login: "Kirish & Ro'yxatdan o'tish",
  noProducts: "Malumotlar yo'q",
  buy: "Sotib olish",
  view: "Ko'rsatish",
  login0: "Kirish",
  register: "Ro'yxatdan o'tish",
  notRegister: "Hisobingiz yo'q. Ro'yxatdan o'tish",
  notLogin: "Allaqachon hisobingiz bor. Tizimga kirish",
  loadMore: "Ko'proq",
  sold: "Sotildi",
  related: "Tegishli mahsulotlar",
  Newest: "Eng yangi",
  Oldest: "Eng qadimgi",
  BestSales: "Eng yaxshi sotuvlar",
  LowPrice: "Past narx",
  HightPrice: "Yuqori narx",
};
